import Link from 'next/link';

import './global.scss';
import Providers from '../components/providers/react-query/client';

export const metadata = {
  title: 'Welcome to next-monorepo',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/server">{'Server Component - No hydration'}</Link>
            </li>
            <li>
              <Link href="/server-client-hydration">
                {'Server Component - With client hydration'}
              </Link>
            </li>
            <li>
              <Link href="/client">{'Client only'}</Link>
            </li>
            <li>
              <Link href="/client-using-react-query">
                {'Client only - using react-query'}
              </Link>
            </li>
          </ul>
        </nav>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
